test: &default

  client_id: AcW2Xt7afrk7vtdDXEVauwvRSL9zLKf2rigMhTSaP-XcOgodqxgWSU-VeeuYJPNweYRTY7u4iFc35UUx
  client_secret: ECCtQLPE_SwpDiJd08_Bxp3RriVbtCC2BryS5YaLlC0dCnX3jQ0mLkM3ibBc83YZQpKOaqRi30uS0xSn
  mode: sandbox

development:
  <<: *default

production:
  # <<: *default
  mode: live
  client_id: AfUj0ciRxE_8YSkM-B99DIueHo_oWwcgUISYG6yDBZXq_-zz35iNN3A1uYK6yVRulOCT3_uG0s0kW01n
  client_secret: ELsWIDJV8nirr6hccNv-Uek_Pe97MjcLw6k2h6nvryI7vKRBJQ2ypA8G_TePZRDMNGN3EvDCXUZNJiJm
