#= require jquery/dist/jquery.min.js
#= require jquery_extensions
#= require jquery.selectors
#= require parallax/deploy/parallax.min
#= require maplace-0.1.3.min
#= require owl_carousel.min
#= require jquery.circle-progress
#= require jquery-animateNumber/jquery.animateNumber.min
#= require jquery.capsChecker.min
#= require jquery.clickout
# require jquery-validation/dist/jquery.validate.min
#= require jquery.tagsinput/src/jquery.tagsinput.js
#= require jquery.serialize-hash
#= require functions
#= require layout
#= require wizard_jquery
#= require dashboard
#= require new_wizard_jquery
