#= require jquery/dist/jquery.min.js
#= require js_extensions
#= require jquery_extensions
#= require jquery.selectors
#= require parallax/deploy/parallax.min
#= require maplace-0.1.3.min
#= require owl_carousel.min
#= require jquery.circle-progress
#= require jquery-animateNumber/jquery.animateNumber.min
#= require jquery.capsChecker.min
#= require jquery.clickout
#= require footable/dist/footable.min
#= require footable/dist/footable.sort.min
# require jquery-validation/dist/jquery.validate.min
#= require jquery.tagsinput/src/jquery.tagsinput.js
# require jquery.serialize-hash
#= require jquery-serialize-object/dist/jquery.serialize-object.min
#= require simpleUpload.min
#= require functions
#= require svg_images_list.coffee.erb
#= require layout
#= require wizard_jquery
#= require dashboard
#= require new_wizard_jquery
#= require jquery.forms
#= require super_new_wizard_jquery
#= require mail_form