#= require jquery/dist/jquery.min.js
#= require js_extensions
#= require evented_class
#= require jquery_extensions
#= require jquery.selectors
#= require parallax/deploy/parallax.min
#= require maplace-0.1.3.min
#= require owl_carousel.min
#= require jquery.circle-progress
#= require jquery-animateNumber/jquery.animateNumber.min
#= require jquery.capsChecker.min
#= require jquery.clickout
#= require footable/dist/footable.min
#= require footable/dist/footable.sort.min
# require jquery-validation/dist/jquery.validate.min
#= require jquery.tagsinput/src/jquery.tagsinput.js
# require jquery.serialize-hash
#= require jquery-serialize-object/dist/jquery.serialize-object.min
#= require jquery_appear/jquery.appear
#= require simpleUpload.min
#= require functions
#= require svg_images_list.coffee.erb
#= require layout
# require wizard_jquery
#= require dashboard
# require new_wizard_jquery
# require jquery.forms
# require super_new_wizard_jquery
# require jquery_forms
# require formify/formify
# require formify/type_converter
# require formify/has_groups
# require formify/has_fields
# require formify/group
# require formify/form
# require formify/jquery
# require formify/inputs/base
# require formify/inputs/string
# require formify/inputs/url
# require formify/inputs/text
# require formify/inputs/radio_button
# require formify/inputs/image_radio_button
# require formify/inputs/collection_input
# require formify/inputs/check_boxes_collection
# require formify/inputs/platforms
# require formify/inputs/files
# require models/project
# require wizard_scripts
#= require mail_form
